\input texinfo   @c -*-texinfo-*-
@c $Id$
@c -- Header --------------------------------------------------

@setfilename repository.info
@settitle Referencia del Repositorio Artístico de CentOS
@documentlanguage es
@afourpaper
@finalout

@c -- Summary description and copyright -----------------------

@copying
Este manual documenta información relevante al desempeño, organización
y administración del repositorio artístico del proyecto CentOS.

Copyright @copyright{} 2009, 2010, 2011 The CentOS Artwork SIG

Se otorga permiso para copiar, distribuir y/o modificar este documento
bajo los términos de la Licencia de Documentación Libre de GNU,
Versión 1.1 o cualquier otra versión posterior publicada por la
Free Software Foundation; con las Secciones Invariantes, con Textos de
Cubierta Delantera, y con los Textos de Cubierta Trasera.  Una copia
de la licencia está incluida en la sección titulada @ref{GNU Free
Documentation License}.  
@end copying

@c -- Titlepage, contents, copyright ---------------------------

@titlepage
@title Repositorio Artístico de CentOS
@subtitle Referencia
@author The CentOS Project 
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@contents

@c -- `Top' node and master menu -------------------------------

@ifnottex
@node Top
@top Referencia del Repositorio Artístico de CentOS
@insertcopying
@end ifnottex

@include repository-menu.texinfo

@c -- The body of the document --------------------------------

@include repository-nodes.texinfo

@c -- The end of the document ---------------------------------

@include repository-index.texinfo

@bye
