\input texinfo   @c -*-texinfo-*-
@c $Id$
@c -- Header --------------------------------------------------

@setfilename =MANUAL_NAME=.info
@settitle =MANUAL_NAME=
@documentlanguage es
@afourpaper
@finalout

@c -- Summary description and copyright -----------------------

@copying
=MANUAL_ABSTRACT=

Copyright @copyright{} =COPYRIGHT_YEAR_LIST= =COPYRIGHT_HOLDER=

Se otorga permiso para copiar, distribuir y/o modificar este documento
bajo los términos de la Licencia de Documentación Libre de GNU,
Versión 1.1 o cualquier otra versión posterior publicada por la
Free Software Foundation; con las Secciones Invariantes siendo su
LISTE SUS TÍTULOS, con Textos de Cubierta Delantera siendo LISTA, y
con los Textos de Cubierta Trasera siendo LISTA. Una copia de la
licencia está incluida en la sección titulada @ref{GNU Free
Documentation License}.  
@end copying

@c -- Titlepage, contents, copyright ---------------------------

@titlepage
@title =MANUAL_NAME=
@subtitle Manual
@author =COPYRIGHT_HOLDER= 
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@contents

@c -- `Top' node and master menu -------------------------------

@ifnottex
@node Top
@top =MANUAL_NAME=
@insertcopying
@end ifnottex

@include =MANUAL_NAME=-menu.texinfo

@c -- The body of the document --------------------------------

@include =MANUAL_NAME=-nodes.texinfo

@c -- The end of the document ---------------------------------

@include =MANUAL_NAME=-index.texinfo

@bye
