The CentOS Project Corporate Visual Identity
============================================
Alain Reguera Delgado <al@centos.org.cu>
v1.0, Jul 2013

Abstract
--------

The CentOS Project Corporate Identity is the ``persona'' of the
organization known as The CentOS Project.  The CentOS Project
Corporate Identity plays a significant role in the way The CentOS
Project, as organization, presents itself to both internal and
external stakeholders. In general terms, The CentOS Project Corporate
Identity expresses the values and ambitions of The CentOS Project
organization, its business, and its characteristics.

The CentOS Project Corporate Identity provides visibility,
recognizability, reputation, structure and identification to The
CentOS Project organization by means of Corporate Design, Corporate
Communication, and Corporate Behaviour.

Corporate Mission
-----------------

The CentOS Project exists to produce The CentOS Distribution, an
Enterprise-class Linux Distribution derived from sources freely
provided to the public by a prominent North American Enterprise Linux
vendor.  The CentOS Distribution conforms fully with the upstream
vendors redistribution policy and aims to be 100% binary compatible.
(The CentOS Distribution mainly changes packages to remove upstream
vendor branding and artwork.).

The CentOS Distribution is developed by a small but growing team of
core developers.  In turn the core developers are supported by an
active user community including system administrators, network
administrators, enterprise users, managers, core Linux contributors
and Linux enthusiasts from around the world.

The CentOS Distribution has numerous advantages including: an active
and growing user community, quickly rebuilt, tested, and QA'ed errata
packages, an extensive mirror network, developers who are contactable
and responsive of a reliable Enterprise-class Linux Distribution,
multiple free support avenues including a
http://wiki.centos.org/[Wiki],
http://www.centos.org/modules/tinycontent/index.php?id=8[IRC Chat],
http://lists.centos.org/[Email Lists],
http://www.centos.org/modules/newbb/[Forums], and a dynamic
http://www.centos.org/modules/smartfaq/[FAQ].

Corporate Graphic Design
------------------------

The corporate design is focused on the effective presentation of
corporate messages. As corporate messages we understand all the
information emitted from the organization; and when we say _all_ we
mean everything that can be perceived through the human senses. The
corporate design takes care of defining what this information is and
controlling the way it goes out the organization producing it.

When the organization doesn't take control over the corporate messages
it produces, the organization is letting that area of its identity to
the unknown and the results might be good or not so good, it is hard
to know.  The issue to see here is that even the organization doesn't
take control over its corporate messages, they are always talking
about the organization.  Taking control of corporate messages is a
decision the organization needs to take by itself, based on its need
of better describe what it is.

In the very specific case of The CentOS Project, we'll concentrate our
attention on corporate messages that reach us through the visual
sense. This is, all the visual manifestations The CentOS Project is
made of. As visual manifestations we understand all the visible media
The CentOS Project uses to manifest its existence on.  At this point
it is necessary to consider what The CentOS Project is, what its
mission is and what it is producing. This, in order to identify which
visual manifestations the organization is demanding attention of
corporate design for.

Inside The CentOS Project we identify and apply corporate design to the following
visual manifestations:

- *The CentOS Distribution:*  This visual manifestation exists to
  cover all actions related to artwork production and re-branding,
  required by The CentOS Distribution in order to comply with
  upstream's redistribution guidelines.

- *The CentOS Web:* This visual manifestation exists to cover all
  actions related to artwork production required by The CentOS Project
  to manifest its existence in the World Wide Web medium.

- *The CentOS Showroom:* This visual manifestation exists to cover all
  actions related to artwork production required by The CentOS Project
  to manifest its existence through media produced industrially (e.g.,
  stationery, clothes, CDs, DVDs, etc.).

The visual manifestations identified above seem to cover most media
required by The CentOS Project, as organization, to show its
existence.  However, other visual manifestations could be added in the
future, as long as they be needed, to cover different areas like
stands, buildings, offices, road transportation or whatever visual
manifestation The CentOS Project touches to show its existence.

Once all visual manifestations have been identified and defined
through design models, it is time to visually remark their connection
with The CentOS Project.  This kind of connection is realized by
applying The CentOS Brand to design models inside visual
manifestations supported through corporate design.

Corporate Communication
-----------------------

The CentOS Project corporate communication is focused on the effective
propagation of corporate messages. Propagation of corporate messages
is closely related to the media the organization uses as vehicle to
distribute its corporate messages.

The CentOS Project corporate communication takes place through the
following visual manifestations:

The CentOS Distribution
~~~~~~~~~~~~~~~~~~~~~~~

This visual manifestation communicates its existence through software
packages.  There are packages that make a remarkable use of images,
packages that make a moderate use of images, and packages that don't
use images at all.  This visual manifestation is focused on providing
The CentOS Project images required by software packages that do use
images in a remarkable way, specially those holding the upstream brand
(e.g., _anaconda_, _grub_, _syslinux_, _gdm_, _kdebase_).

- The Community Enterprise Operating System itself (communicates the
  essense of The CentOS Project existence.).

- Release Schema (Lifetime) and all the stuff related (e.g., Release
  Notes, Documentation, Erratas, etc.).

The CentOS Web
~~~~~~~~~~~~~~

This visual manifestation communicates its existence through web
applications.  These web applications are free software and come from
different providers which distribute their work with predefined visual
styles.  Frequently, these predefined visual styles have no visual
relation among themselves and introduce some visual contradictions
when they all are put together.  Removing these visual contradictions
is object of work for this visual manifestation.

- The CentOS Chat.
- The CentOS Mailing Lists.
- The CentOS Forums.
- The CentOS Wiki.
- Special Interest Groups (SIGs).
- Social Events, Interviews, Conferences, etc.
- The extensive network of mirrors available for downloading ISO files
  as well as RPMs and SRPMs used to build them up in different
  architectures.

The CentOS Showroom
~~~~~~~~~~~~~~~~~~~

This visual manifestation communicates its existence through
production of industrial objects carrying The CentOS Brand.  These
branded objects are directed to be distributed on social events and/or
shops. They provide a way of promotion and commercialization that may
help to reduce The CentOS Project expenses (e.g., electrical power,
hosting, servers, full-time-developers, etc.), in a similar way as
donations may do.

- Stationery (e.g., Posters, Stickers, CD Lables and Sleeves).
- Clothes (e.g., Shirts, T-shirts, Pullovers, Caps).
- Installation media (e.g., CDs, DVD, Pendrives).

Corporate Behaviour
-------------------
The CentOS Project corporate behaviour is focused on the effective
interaction of each member involved in the organization (e.g., core
developers, community members, etc.).  It is related to ethics and
politics used to do the things inside the organization. It is related
to the sense of direction chosen by the organization and they way the
organization projects itself to achieve it.

The CentOS Project corporate behaviour takes place through The CentOS
Project corporate communication, as described above.

Corporate Structure
-------------------
The CentOS Project corporate structure is based on a Monolithic
Corporate Visual Identity Structure. In this configuration, one unique
name and one unique visual style is used in all visual manifestation
The CentOS Project is made of.

In a monolithic corporate visual identity structure, internal and
external stakeholders use to feel a strong sensation of uniformity,
orientation, and identification with the organization. No matter if
you are visiting web sites, using the distribution, or acting on
social events, the one unique name and one unique visual style
connects them all to say: Hey! we are all part of The CentOS Project.

Other corporate structures for The CentOS Project have been considered
as well. Such is the case of producing one different visual style for
each major release of The CentOS Distribution. This structure isn't
inconvenient at all, but some visual contradictions could be
introduced if it isn't applied correctly and we need to be aware of
it. To apply it correctly, we need to know what The CentOS Project is
made of.

The CentOS Project, as organization, is mainly made of (but not
limited to) three visual manifestions: The CentOS Distribution, The
CentOS Web and The CentOS Showroom.  Inside The CentOS Distribution
visual manifestations, The CentOS Project maintains near to four
different major releases of The CentOS Distribution, parallely in
time.  However, inside The CentOS Web visual manifestations, the
content is produced for no specific release information (e.g., there
is no a complete web site for each major release of The CentOS
Distribution individually, but one web site to cover them all).
Likewise, the content produced in The CentOS Showroom is industrially
created for no specific release, but The CentOS Project in general.

In order to produce the The CentOS Project Monolithic Corporate Visual
Identity Structure correctly, we need to concider all the visual
manifestations The CentOS Project is made of, not just one of them.
If one different visual style is implemented for each major release of
The CentOS Distribution, which one of those different visual styles
would be used to cover the remaining visual manifestations The CentOS
Project is made of (e.g., The CentOS Web and The CentOS Showroom)?

Probably you are thinking: yes, I see your point, but The CentOS Brand
connects them all already, why would we need to join them up into the
same visual style too, isn't it more work to do, and harder to
maintain?

Harder to maintain, more work to do, probably. Specially when you
consider that The CentOS Project has proven stability and consistency
through time and, that, certainly, didn't come through swinging
magical wands or something but hardly working out to automate tasks
and providing maintenance through time.  With that in mind, I consider
The CentOS Project Corporate Visual Identity Structure must be
consequent with such stability and consistency tradition.  It is true
that The CentOS Brand does connect all the visual manifestations it is
present on, but that connection is strengthened if one unique visual
style backups it.  In fact, whatever thing you do to strength the
visual connection among The CentOS Project visual manifestations would
be very good in favor of The CentOS Project recognition.

Obviously, having just one visual style in all visual manifestations
for eternity would be a very boring thing and would give the idea of a
visually outdated project. So, there is no problem on creating new
visual styles for each new major release of The CentOS Distribution,
in order to refresh The CentOS Distribution visual style; the problem
itself is in not propagating the new visual style created for the new
release of The CentOS Distribution to all other visual manifestations
The CentOS Project is made of, in a way The CentOS Project could be
recognized no matter what visual manifestation be in front of us. Such
lack of uniformity is what introduces the visual contradiction we
would be precisely trying to solve by mean of themes production in The
CentOS Artwork Repository.

// vim: set syntax=asciidoc:
