@node GNU General Public License
@section Licencia Pública General de GNU
@cindex Licencia pública general GNU
@include trunk/Documentation/Models/Texinfo/Default/Licenses/GPL.texinfo

@node GNU Free Documentation License
@section Licencia de Documentación Libre de GNU
@cindex Licencia documentación libre GNU
@include trunk/Documentation/Models/Texinfo/Default/Licenses/GFDL.texinfo
