@node GNU General Public License
@section GNU General Public License
@cindex GNU General Public License
@include trunk/Scripts/Functions/Help/Backends/Texinfo/Templates/en_US/Licenses/GPL.texinfo

@node GNU Free Documentation License
@section GNU Free Documentation License
@cindex GNU Free Documentation License
@include trunk/Scripts/Functions/Help/Backends/Texinfo/Templates/en_US/Licenses/GFDL.texinfo
