tcar_getConfigValue(1)
======================

== Name

tcar_getConfigValue - Standardize options retrieval from configuration
files.

== Synopsis

*tcar_getConfigValue FILE SECTION OPTION*

== Description

The *tcar_getConfigValue* function standardizes the way option values
are retrieved from configuration files. As convention,
*tcar_getConfigValue* uses the output produced by
*tcar_getConfigLines* as input to retrieve the option values. As
convention, in +option = "value"+ lines, the values retrieved are
always on the right side. The values retrieved are also output without
quotation and translation markers already expanded.

The *tcar_getConfigValue* function accepts the
following arguments:

FILE::
    This argument specifies the absolute path to the configuration
    file you want to retrieve the value from. For example,
    ``+${TCAR_WORKDIR}/Identity/Models/Themes/Default/Distro/5/Anaconda/branding.conf+''.

SECTION::
    This argument specifies the name of the section related to the
    configuration line you want to retrieve the value from. For
    example, ``symbols'' without brackets.

OPTION::
    This argument specifies the name of the option you want to
    retrieve the value from.

Use the *tcar_getConfigValue* function whenever you want to retrieve
values from configuration files in a controlled way.

== Bugs

See https://centos.org.cu/bugs/

== Authors

The *tcar_checkFiles* function has received contributions from the
following people:

- Alain Reguera Delgado <al@centos.org.cu>, =COPYRIGHT_YEAR_LIST=

== License

Copyright (C) =COPYRIGHT_YEAR_LIST= =COPYRIGHT_HOLDER=

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

// vim: set syntax=asciidoc:
