tcar_checkRepoDirSource(1)
==========================

== Name

tcar_checkRepoDirSource - Standardize the working copy's absolute path
construction.

== Synopsis

tcar_checkRepoDirSource "LOCATION"

== Description

The *tcar_checkRepoDirSource* function standardizes the path
construction to directories inside it the working copy, using absolute
paths.  This function transforms relative paths passed as non-option
arguments to *centos-art.sh* script command-line into absolute paths
inside the working copy and verifies whether they really exist as
directories inside the working copy or not. If the path provided
doesn't exist as directory inside the working copy, the script will
finish its execution immediately with an error message. Otherwise, if
the directory exists, the variable +TCAR_ARGUMENTS+ is redefined with
the related absolute path for further use.

Use the *tcar_checkRepoDirSource* function whenever you need to be
sure that non-option arguments passed to *centos-art.sh* script
command-line will always point to directories inside the working copy.

== Bugs

See https://centos.org.cu/bugs/

== Authors

The *tcar_checkRepoDirSource* function has received contributions from
the following people:

- Alain Reguera Delgado <al@centos.org.cu>, =COPYRIGHT_YEAR_LIST=

== License

Copyright (C) =COPYRIGHT_YEAR_LIST= =COPYRIGHT_HOLDER=

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

// vim: set syntax=asciidoc:
