Preface
-------

Every single corporation, organization, society or community has its
own unique identity, even though their members don't take an
intentional control over it.  Having an strong identity plays a
significant role in the way the organization presents itself to both
internal and external stakeholders. It expresses the values and
ambitions of the organization, its business, and its characteristics.
It provides visibility, recognizability, reputation, structure and
identification to the organization by means of graphic design,
communication, and behavior.  This kind of control is expensive and
not all organizations are able to maintain it.  Nevertheless,
organizations can assume an acceptable degree of compromise and, based
on pragmatic facts, work on a consistent idea that can be
progressively improved through time.

To work on a consistent idea of identity, the organization defines its
mission and makes it public in a place everyone can read. Then, the
organization identifies each single manifestation where it shows its
existence on in order take control over their presentations. The
presentation of one organization is controlled by graphical components
like names, symbols, colors, logotypes and, social components like
rituals, behaviours and communication. All these components are
interrelated and affect the organization identity.

To effectively and efficiently control each single manifestation the
organization is made of, the organization creates and publishes its
``Identity Manual.'' In such a manual, the organization clearly
identifies the visual manifestations it wants to take control of and
how exactly to do that. It is a tool. It is a reference manual that
describes the organization itself.

Trough the years the CentOS community has shown a growing interest on
helping to develop The CentOS Project. Some people seem to be very
clear about what the project's needs are and how to maintain it being
a highly stable project, but others however don't get what The CentOS
Project is (even it is explained time after time) and sometimes decide
to put their efforts in the wrong direction making everything to be a
waste of time and source of distraction from what is really needed. In
order for the community to concentrate efforts in the right direction
effectively and efficiently, the community needs a visible reference
describing what these right directions are.

_The CentOS Project Identity Manual_ identifies and describes the key
manifestations of The CentOS Project identity.  This manual answers
the question ``What can I do for The CentOS Project?'' identifying
different work lines that relate one another and everyone can join in.
It describes a working environment where there are graphic designers
producing images, documenters producing documentation manuals (whose
use images produced by graphic designers), programmers producing
automation scripts (needed to standardize production tasks),
translators localizing source files created by graphic designers,
documenters and programmers and packagers collecting information from
all work lines for building RPM packages.

_The CentOS Project Identity Manual_ organizes content in two main
parts. The first part of the book (<<identity>>) describes conceptual
ideas about The CentOS Project corporate identity (e.g., mission,
names, symbols, colors and visual structure). It sets the background
information you need in order to understand the second part of the
book (<<repository>>) which describes the implementation of The CentOS
Project corporate identity (e.g., how to produce images, translations,
documents and packages).

Copyright
~~~~~~~~~

Copyright (C) 2009-2013 The CentOS Artwork SIG.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in <<licenses-gfdl>>.

Feedback
~~~~~~~~

_The CentOS Project Identity Manual_ is a community effort and it
needs of your collaboration in order to get improved. If you find
problems in this book, please send your corrections, comments and
suggestions to CentOS artwork mailing list
(mailto:centos-artwork@centos.org[centos-artwork@centos.org]). This is
the central vain of discussion about The CentOS Project identity
inside the CentOS community.

When you send corrections to CentOS artwork mailing list, please be
sure to define what the problem exactly is, define where it is, and
the possible solution. This increases the chances that someone could
take it and implement it. Poorly described problems might be skipped
by people responsible of implementing the solutions. You might also
find useful to propose your initiatives as a community effort so they
can be validated and supported by the community itself.

// vim: set syntax=asciidoc:
