@node GNU General Public License
@section Licencia Pública General de GNU
@cindex Licencia pública general GNU
@include trunk/Scripts/Functions/Help/Templates/es_ES/Licenses/GPL.texinfo

@node GNU Free Documentation License
@section Licencia de Documentación Libre de GNU
@cindex Licencia documentación libre GNU
@include trunk/Scripts/Functions/Help/Templates/es_ES/Licenses/GFDL.texinfo
