\input texinfo   @c -*-texinfo-*-
@c -- Header --------------------------------------------------

@setfilename tcar-fs.info
@settitle The CentOS Artwork Repository File System
@documentlanguage en
@afourpaper
@finalout

@c -- Variables -----------------------------------------------

@set TCENTOS    The Community Enterprise Operating System
@set TCPROJ     @url{http://www.centos.org/, The CentOS Project}
@set TCWIKI     @url{http://wiki.centos.org/, The CentOS Wiki}
@set TCMLISTS   @url{http://lists.centos.org/, The CentOS Mailing Lists}
@set TCBUGS     @url{http://bugs.centos.org/, The CentOS Bugs}
@set TCMIRRORS  @url{http://mirrors.centos.org/, The CentOS Mirrors}
@set TCPLANET   @url{http://planet.centos.org/, The CentOS Planet}
@set TCFORUMS   @url{http://forums.centos.org/, The CentOS Forums}
@set TCINFOML   @email{centos-info@@centos.org, The CentOS Information Mailing List}
@set TCDEVSML   @email{centos-devel@@centos.org, The CentOS Developers Mailing List}
@set TCDOCSML   @email{centos-docs@@centos.org, The CentOS Documentation Mailing List}
@set TCARTWML   @email{centos-artwork@@centos.org, The CentOS Artwork Mailing List}
@set TCL10NML   @email{centos-l10n@@centos.org, The CentOS Localization Mailing List}
@set TCAR       @url{https://projects.centos.org/svn/artwork/, The CentOS Artwork Repository}
@set TCAS       @url{https://projects.centos.org/trac/artwork/, The CentOS Artwork SIG}

@set TCPCVI     The CentOS Project Corporate Visual Identity
@set TCPCI      The CentOS Project Corporate Identity
@set TCPCVIS    The CentOS Project Corporate Visual Identity Structure
@set TCPCMVIS   The CentOS Project Monolithic Corporate Visual Identity Structure

@set TCD        The CentOS Distribution

@c -- Summary description and copyright -----------------------

@copying
This manual describes the directories inside @value{TCAR}. You can use
this manual as reference to know where to store or look for
information inside your working copy of @value{TCAR}.

Copyright @copyright{} 2009, 2010, 2011 The CentOS Project

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A
copy of the license is included in the section entitled @ref{GNU Free
Documentation License}.
@end copying

@c -- Titlepage, contents, copyright ---------------------------

@titlepage
@title The CentOS Artwork Repository File System
@subtitle Reference
@author The CentOS Project
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@contents

@c -- `Top' node and master menu -------------------------------

@ifnottex
@node Top
@top The CentOS Artwork Repository File System
@insertcopying
@end ifnottex

@include tcar-fs-menu.texinfo

@c -- The body of the document --------------------------------

@include tcar-fs-nodes.texinfo

@c -- The end of the document ---------------------------------

@include Licenses/chapter.texinfo
@include tcar-fs-index.texinfo

@bye
