@node Trunk
@chapter The @file{trunk} Directory
@cindex The @file{trunk} Directory

@c -- Chapter Introduction
The @file{trunk} directory structure implements the Subversion's trunk
concept in a trunk, branches, tags repository structure. It provides
the main development line inside @value{TCAR} and is made of the
following components:

@c -- Chapter Menu
@include Trunk/chapter-menu.texinfo

@c -- Chapter Nodes
@include Trunk/chapter-nodes.texinfo
