@node Trunk Identity Images
@section @file{trunk/Identity/Images}
@cindex Trunk identity images

The @file{trunk/Identity/Images} directory exists to store all image
files (e.g., PNG, JPG, PPM, etc.) related to @value{TCPCVI}.

The @file{trunk/Identity/Images} directory and the files inside it
aren't under version control.

The @file{trunk/Identity/Images} directory contains no file, but the
following directories to organize files:

@c -- <[centos-art(SeeAlso)
@itemize
@item @ref{Trunk Identity Images Brands}
@item @ref{Trunk Identity Images Themes}
@end itemize
@c -- ]>

Content rendition inside @file{trunk/Identity/Images/Brands/Logos}
directory takes place through the following command:

@verbatim
centos-art render trunk/Identity/Images --dont-commit-changes
@end verbatim
