@node Trunk Identity Fonts
@section @file{trunk/Identity/Fonts}
@cindex Trunk identity fonts

The @file{trunk/Identity/Fonts} directory exists to organize
typographies used inside @value{TCPCVI}. Most fonts stored inside this
location are TrueType Fonts (@file{.ttf}) that aren't available inside
@file{/usr/share/fonts} directory.

@c -- describe, in one paragraph, what a font is.

In order for fonts to be available inside programs like GIMP and
Inkscape, font files should be stored either in
@file{/usr/share/fonts} or @file{~/.fonts} directory. These locations
are out of @value{TCAR} and doesn't provide version control by
themselves. In order for using version controlled fonts inside
programs like GIMP and Inkscape, we store font related files under
@file{trunk/Identity/Fonts} directory and create links to them from
@file{~/.fonts} directory.

@float Example, trunk-identity-fonts-1
@verbatim
trunk/Identity/Fonts
`-- denmark.ttf (file) <-- ~/.fonts/denmark.ttf (link)
@end verbatim
@caption{Relation between fonts inside the workstation.}
@end float

The creation and maintainance of links related to fonts inside the
working copy are automated by @code{prepare} functionality of
@command{centos-art.sh} script.

@image{trunk/Identity/Images/Manuals/Fonts/dejavu-lgc,443pt,,,}

Inside @value{TCPCVI}, the @samp{DejaVu LGC} typography is used as
default typography in all visual manifestations. The @samp{DejaVu LGC}
typography comes with @value{TCD} so there is no need to store it in
@file{trunk/Identity/Fonts} for you to use.

@image{trunk/Identity/Images/Manuals/Fonts/denmark,443pt,,,}

Inside @value{TCPCVI}, the @samp{Denmark} typography is used as base
to build The CentOS Logo (i.e., the main graphic design that
connects/identifies all visual manifestations related to The CentOS
Project). The @samp{Denmark} typography doesn't come with @value{TCD}
so it is store in @file{trunk/Identity/Fonts} for you to use.

The license information of @samp{Denmark} typography isn't very clear,
at least not as clear as the one in @samp{DejaVu LGC} typography is.
Using a typography with a doubtful license might put in risk the
content produced from it.  To prevent such issues, it would be better
to move on from @samp{Denmark} typography to another typography (free,
preferably) that retain the same visual style of @samp{Denmark}, but
with a clearer copyright and license notice.
