@node Trunk Identity
@section @file{trunk/Identity}
@cindex Trunk identity

The @file{trunk/Identity} directory describes @value{TCPCI}, what it
is and the components it is made of.

@value{TCPCI} is the ``persona'' of the organization known as The
CentOS Project.  The CentOS Project Corporate Identity plays a
significant role in the way The CentOS Project, as organization,
presents itself to both internal and external stakeholders. In general
terms, The CentOS Project Corporate Identity expresses the values and
ambitions of The CentOS Project organization, its business, and its
characteristics.  @value{TCPCI} provides visibility, recognizability,
reputation, structure and identification to The CentOS Project by
means of Corporate Design, Corporate Communication, and Corporate
Behaviour.

From Corporate Design, Corporate Communication and Corporate
Behaviour, it is the Corporate Design the one organized inside
@file{trunk/Identity} directory through the following components:

@menu
* Trunk Identity Brushes::
* Trunk Identity Fonts::
* Trunk Identity Images::
* Trunk Identity Models::
* Trunk Identity Palettes::
* Trunk Identity Patterns::
@comment --- Removed(* Trunk Identity Webenv::) ---
@end menu
