@node Trunk Identity Images Brands Types
@section @file{trunk/Identity/Images/Brands/Types}
@cindex Trunk identity images brands types

The @file{trunk/Identity/Images/Brands/Types} exists to organize
images related to The CentOS Symbol, in different formats (e.g., PNG,
JPG, PDF, TIF, XBM, XPM) and dimensions. 

The CentOS Type is the typographical part of The CentOS Logo.
Comparing with both The CentOS Logo and The CentOS Symbol, The CentOS
Type by its own, provides poor visual connection between images that
intend to be recongnized as a monolithic part of @value{TCPROJ} and
shouldn't be used alone. Instead, The CentOS Logo or The CentOS Symbol
are prefered.  The CentOS Symbol must be exactly the same everytime it
is printed out and a route to reproduce it in such a way must be
available so as to avoid reproduction mistakes when images are branded
with it.

The @file{trunk/Identity/Images/Brands/Types} directory and the files
inside it aren't under version control. Files in this location are
mainly used to build The CentOS Logo from combining both The CentOS
Type and The CentOS Symbol in specific situations that might be needed
doing so.

The @file{trunk/Identity/Images/Brands/Types} directory contains files
used by no package, as far as we've found out.

The @file{trunk/Identity/Images/Brands/Types} directory organizes
files under directories numerically named (e.g., @file{48}, @file{64},
@file{128}, etc.).  Inside these directories, image files are stored
in specific heights and named as
@file{centos-<something>.<extension>}, where @code{<somthing>}
describes the file content and @code{<extension>} sets the file
extension. In all cases, the directory name can be used as reference
to determine the image height of files stored inside.  For example,
the directory @file{48} stores image files of 48 pixels height in
different formats.

Content rendition inside @file{trunk/Identity/Images/Brands/Types}
directory takes place through the following command:

@verbatim
centos-art render trunk/Identity/Images/Brands/Types --dont-commit-changes
@end verbatim
