@node Trunk Identity Images Brands
@section @file{trunk/Identity/Images/Brands}
@cindex Trunk identity images brands

The @file{trunk/Identity/Images/Brands} directory exists to organize
brand information related to @value{TCPROJ}.

The @file{trunk/Identity/Images/Brands} directory is organized in the
following components:

@menu
* Trunk Identity Images Brands Logos::
@end menu
