@node Trunk Scripts Functions
@section @file{trunk/Scripts/Functions}
@cindex Trunk scripts functions

The @file{trunk/Scripts/Functions} directory exists to organize
task-specific functionalities related to the @command{centos-art.sh}
script.

The @file{trunk/Scripts/Functions} directory and all files inside it
are under version control.

Content rendition inside `trunk/Scripts/Functions' directory is not
supported.

Inside @file{trunk/Scripts/Functions} directory, functionalities are
organized in the following directories:

@c -- <[centos-art(SeeAlso)
@itemize
@item @ref{Trunk Scripts Functions Prepare}
@end itemize
@c -- ]>
