\input texinfo   @c -*-texinfo-*-
@c $Id$
@c -- Header --------------------------------------------------

@setfilename =MANUAL_NAME=.info
@settitle =MANUAL_TITLE=
@documentlanguage =LOCALE_LL=
@afourpaper
@finalout

@c -- Variables -----------------------------------------------

@set TCENTOS    The Community Enterprise Operating System
@set TCPROJ     @url{http://www.centos.org/, The CentOS Project}
@set TCWIKI     @url{http://wiki.centos.org/, The CentOS Wiki}
@set TCMLISTS   @url{http://lists.centos.org/, The CentOS Mailing Lists}
@set TCBUGS     @url{http://bugs.centos.org/, The CentOS Bugs}
@set TCMIRRORS  @url{http://mirrors.centos.org/, The CentOS Mirrors}
@set TCPLANET   @url{http://planet.centos.org/, The CentOS Planet}
@set TCFORUMS   @url{http://forums.centos.org/, The CentOS Forums}
@set TCINFOML   @email{centos-info@@centos.org, The CentOS Information Mailing List}
@set TCDEVSML   @email{centos-devel@@centos.org, The CentOS Developers Mailing List}
@set TCDOCSML   @email{centos-docs@@centos.org, The CentOS Documentation Mailing List}
@set TCARTWML   @email{centos-artwork@@centos.org, The CentOS Artwork Mailing List}
@set TCL10NML   @email{centos-l10n@@centos.org, The CentOS Localization Mailing List}
@set TCAR       @url{https://projects.centos.org/svn/artwork/, The CentOS Artwork Repository}
@set TCAS       @url{https://projects.centos.org/trac/artwork/, The CentOS Artwork SIG}

@c -- Summary description and copyright -----------------------

@copying
=MANUAL_ABSTRACT=

Copyright @copyright{} =COPYRIGHT_YEAR_LIST= @value{TCAS}

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A
copy of the license is included in the section entitled @ref{GNU Free
Documentation License}.
@end copying

@c -- Titlepage, contents, copyright ---------------------------

@titlepage
@title =MANUAL_TITLE=
@subtitle =MANUAL_SUBTITLE=
@author @value{TCAS}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@contents

@c -- `Top' node and master menu -------------------------------

@ifnottex
@node Top
@top =MANUAL_TITLE=
@insertcopying
@end ifnottex

@include =MANUAL_NAME=-menu.texinfo

@c -- The body of the document --------------------------------

@include =MANUAL_NAME=-nodes.texinfo

@c -- The end of the document ---------------------------------

@include Licenses/chapter.texinfo
@include =MANUAL_NAME=-index.texinfo

@bye
