@node Introduction
@chapter Introduction
@cindex Introduction

Welcome to The CentOS Artwork Repository manual.

The CentOS Artwork Repository manual describes how The CentOS Project
corporate visual identity is organized and produced inside The CentOS
Artwork Repository (@url{https://projects.centos.org/svn/artwork/}).
If you are looking for a comprehensive guide for understanding how The
CentOS Project corporate visual identity is produced, this is the
manual for you.

This manual assumes you have a basic understanding of The CentOS
Distribution. If you need help with CentOS, refer to the help page on
The CentOS Wiki (@url{http://wiki.centos.org/Help}) for a list of
different places you can find help.

@include Introduction/chapter-menu.texinfo
@include Introduction/chapter-nodes.texinfo
