@node trunk Identity
@section trunk/Identity
@cindex trunk Identity
@include trunk/Identity.texi

@node trunk Identity Brands
@section trunk/Identity/Brands
@cindex trunk Identity Brands
@include trunk/Identity/Brands.texi

@node trunk Scripts
@section trunk/Scripts
@cindex trunk Scripts
@include trunk/Scripts.texi

@node trunk Scripts Bash
@section trunk/Scripts/Bash
@cindex trunk Scripts Bash
@include trunk/Scripts/Bash.texi

@node trunk Scripts Bash Config
@section trunk/Scripts/Bash/Config
@cindex trunk Scripts Bash Config
@include trunk/Scripts/Bash/Config.texi

@node trunk Translations
@section trunk/Translations
@cindex trunk Translations
@include trunk/Translations.texi

