@node trunk Identity
@section trunk/Identity
@cindex trunk identity
@include trunk/Identity.texi

@node trunk Identity Brands
@section trunk/Identity/Brands
@cindex trunk identity brands
@include trunk/Identity/Brands.texi

@node trunk Scripts
@section trunk/Scripts
@cindex trunk scripts
@include trunk/Scripts.texi

@node trunk Scripts Bash
@section trunk/Scripts/Bash
@cindex trunk scripts bash
@include trunk/Scripts/Bash.texi

@node trunk Scripts Bash Config
@section trunk/Scripts/Bash/Config
@cindex trunk scripts bash config
@include trunk/Scripts/Bash/Config.texi

@node trunk Translations
@section trunk/Translations
@cindex trunk translations
@include trunk/Translations.texi

