@node History
@section History
@cindex History
@include Introduction/history.texinfo

@node Authors
@section Authors
@cindex Authors
@include Introduction/authors.texinfo

@node Copying Conditions
@section Copying Conditions
@cindex Copying conditions
@include Introduction/copying.texinfo

@node Document Convenctions
@section Document Convenctions
@cindex Document convenctions
@include Introduction/doc-convenctions.texinfo

@node Repository Convenctions
@section Repository Convenctions
@cindex Repository convenctions
@include Introduction/repo-convenctions.texinfo

@node Feedback
@section Send in Your Feedback
@cindex Feedback
@include Introduction/feedback.texinfo

