@node Directories branches
@section El directorio @file{branches}
@cindex Directories branches
@include Directories/branches.texinfo

@node Directories tags
@section El directorio @file{tags}
@cindex Directories tags
@include Directories/tags.texinfo

@node Directories trunk
@section El directorio @file{trunk}
@cindex Directories trunk
@include Directories/trunk.texinfo

@node Directories trunk Scripts
@section El directorio @file{trunk/Scripts}
@cindex Directories trunk Scripts
@include Directories/trunk/Scripts.texinfo

