@node Directories
@chapter Los directorios del repositorio
@cindex Directories
@include Directories/chapter-menu.texinfo
@include Directories/chapter-nodes.texinfo

El repositorio artístico del proyecto CentOS usa directorios para
organizar ficheros y describir ideas relacionadas a su identidad
corporativa. Estas ideas están explicadas en las entradas de
documentación relacionadas a cada uno de los directorios existentes en
el repositorio.

En este capítulo usted aprenderá cuáles son los diferentes directorios
que existen dentro del repositorio, para qué son y cómo pude
utilizarlos. Con estos objetivos, la siguiente lista de directorios
está disponible para que usted explore:
