@node Directories trunk
@section El directorio @file{trunk}
@cindex Directories trunk
@include Directories/trunk.texinfo

@node Directories trunk Identity
@section El directorio @file{trunk/Identity}
@cindex Directories trunk Identity
@include Directories/trunk/Identity.texinfo

@node Directories trunk Scripts
@section El directorio @file{trunk/Scripts}
@cindex Directories trunk Scripts
@include Directories/trunk/Scripts.texinfo

@node Directories trunk Scripts Functions
@section El directorio @file{trunk/Scripts/Functions}
@cindex Directories trunk Scripts Functions
@include Directories/trunk/Scripts/Functions.texinfo

@node Directories trunk Scripts Functions Help
@section El directorio @file{trunk/Scripts/Functions/Help}
@cindex Directories trunk Scripts Functions Help
@include Directories/trunk/Scripts/Functions/Help.texinfo

@node Directories trunk Scripts Functions Render
@section El directorio @file{trunk/Scripts/Functions/Render}
@cindex Directories trunk Scripts Functions Render
@include Directories/trunk/Scripts/Functions/Render.texinfo

