@node Directories
@chapter Los directorios del repositorio
@cindex Directories
@include Directories/chapter-intro.texinfo
@include Directories/chapter-menu.texinfo
@include Directories/chapter-nodes.texinfo

El repositorio artístico del proyecto CentOS usa directorios para
organizar conceptos sobre su identidad corporativa. Estos conceptos
están explicados an la entrada de documentación relacionada a cada
directorio.

En este capítulo usted aprenderá cuáles son los directorios del
repositorio artístico de CentOS, para qué son y cómo pude hacer uso de
ellos. Para satisfacer tal objetivo, la siguiente lista de directorios
está disponible para que usted pueda explorar:
