@node Branches
@chapter The @file{branches} Directory
@cindex The @file{branches} Directory

@c -- Chapter Introduction
This directory implements the Subversion's branches concept in a
trunk, branches, tags repository structure. The @file{branches}
directory structure provides an intermediate space for creating
temporal changes that might be later merged into @file{trunk}
directory structure (@pxref{Trunk}).

@c -- Chapter Menu
@include Branches/chapter-menu.texinfo

@c -- Chapter Nodes
@include Branches/chapter-nodes.texinfo
