locale.conf.sh(1)
=================

Name
----

locale.conf.sh - Initialize environment variables for locale module.

Synopsis
--------

*declare* [*-xr*] _NAME_[=_VALUE_] ...

Options
-------

*-r*::
    Make _NAME_ read-only.  These names cannot then be assigned values
    by subsequent assignment statements or unset.
*-x*::
    Mark _NAME_ for export to subsequent commands via the environment.

Variables
---------

The *locale.conf.sh* file contains the following environment
variables:

_MODULE_VERSION_::
    Specifies the module's version. This variable is read-only.
_ACTIONS_::
    Specifies the command-line actions. This variable is used to
    gather the list of action-related options passed to locale module
    through the command-line.
TCAR_SCRIPT_MODULES_BASEDIR::
    Specifies the locale modules' base directory. This is the
    directory where the first level locale modules are stored in. You
    must set this variable to ``${MODULE_DIR_MODULES}'' if you want to
    use locale modules.

Author
------

Written by mailto:al@centos.org.cu[Alain Reguera Delgado]

Copyright
---------

Copyright (C) 2009-2013 The CentOS Project

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

See Also
--------

bash(1)

// vim: set syntax=asciidoc:
