@node trunk Identity
@section trunk/Identity
@cindex trunk Identity
@include trunk/Identity.texi

@node trunk Identity Brands
@section trunk/Identity/Brands
@cindex trunk Identity Brands
@include trunk/Identity/Brands.texi

@node trunk Identity Fonts
@section trunk/Identity/Fonts
@cindex trunk Identity Fonts
@include trunk/Identity/Fonts.texi

@node trunk Identity Icons
@section trunk/Identity/Icons
@cindex trunk Identity Icons
@include trunk/Identity/Icons.texi

@node trunk Identity Isolinux
@section trunk/Identity/Isolinux
@cindex trunk Identity Isolinux
@include trunk/Identity/Isolinux.texi

@node trunk Identity Models
@section trunk/Identity/Models
@cindex trunk Identity Models
@include trunk/Identity/Models.texi

@node trunk Identity Models Css
@section trunk/Identity/Models/Css
@cindex trunk Identity Models Css
@include trunk/Identity/Models/Css.texi

@node trunk Identity Models Html
@section trunk/Identity/Models/Html
@cindex trunk Identity Models Html
@include trunk/Identity/Models/Html.texi

@node trunk Identity Models Img Promo Web
@section trunk/Identity/Models/Img/Promo/Web
@cindex trunk Identity Models Img Promo Web
@include trunk/Identity/Models/Img/Promo/Web.texi

@node trunk Identity Models Tpl
@section trunk/Identity/Models/Tpl
@cindex trunk Identity Models Tpl
@include trunk/Identity/Models/Tpl.texi

@node trunk Identity Models Tpl Promo Web
@section trunk/Identity/Models/Tpl/Promo/Web
@cindex trunk Identity Models Tpl Promo Web
@include trunk/Identity/Models/Tpl/Promo/Web.texi

@node trunk Identity Models Xcf
@section trunk/Identity/Models/Xcf
@cindex trunk Identity Models Xcf
@include trunk/Identity/Models/Xcf.texi

@node trunk Identity Release
@section trunk/Identity/Release
@cindex trunk Identity Release
@include trunk/Identity/Release.texi

@node trunk Identity Themes
@section trunk/Identity/Themes
@cindex trunk Identity Themes
@include trunk/Identity/Themes.texi

@node trunk Identity Themes Models
@section trunk/Identity/Themes/Models
@cindex trunk Identity Themes Models
@include trunk/Identity/Themes/Models.texi

@node trunk Identity Themes Models Alternative
@section trunk/Identity/Themes/Models/Alternative
@cindex trunk Identity Themes Models Alternative
@include trunk/Identity/Themes/Models/Alternative.texi

@node trunk Identity Themes Models Default
@section trunk/Identity/Themes/Models/Default
@cindex trunk Identity Themes Models Default
@include trunk/Identity/Themes/Models/Default.texi

@node trunk Identity Themes Models Default Distro
@section trunk/Identity/Themes/Models/Default/Distro
@cindex trunk Identity Themes Models Default Distro
@include trunk/Identity/Themes/Models/Default/Distro.texi

@node trunk Identity Themes Models Default Distro Anaconda
@section trunk/Identity/Themes/Models/Default/Distro/Anaconda
@cindex trunk Identity Themes Models Default Distro Anaconda
@include trunk/Identity/Themes/Models/Default/Distro/Anaconda.texi

@node trunk Identity Themes Models Default Promo
@section trunk/Identity/Themes/Models/Default/Promo
@cindex trunk Identity Themes Models Default Promo
@include trunk/Identity/Themes/Models/Default/Promo.texi

@node trunk Identity Themes Models Default Web
@section trunk/Identity/Themes/Models/Default/Web
@cindex trunk Identity Themes Models Default Web
@include trunk/Identity/Themes/Models/Default/Web.texi

@node trunk Identity Themes Motifs
@section trunk/Identity/Themes/Motifs
@cindex trunk Identity Themes Motifs
@include trunk/Identity/Themes/Motifs.texi

@node trunk Identity Themes Motifs Flame
@section trunk/Identity/Themes/Motifs/Flame
@cindex trunk Identity Themes Motifs Flame
@include trunk/Identity/Themes/Motifs/Flame.texi

@node trunk Identity Themes Motifs Modern
@section trunk/Identity/Themes/Motifs/Modern
@cindex trunk Identity Themes Motifs Modern
@include trunk/Identity/Themes/Motifs/Modern.texi

@node trunk Identity Themes Motifs Modern Backgrounds
@section trunk/Identity/Themes/Motifs/Modern/Backgrounds
@cindex trunk Identity Themes Motifs Modern Backgrounds
@include trunk/Identity/Themes/Motifs/Modern/Backgrounds.texi

@node trunk Identity Themes Motifs Modern Backgrounds Img
@section trunk/Identity/Themes/Motifs/Modern/Backgrounds/Img
@cindex trunk Identity Themes Motifs Modern Backgrounds Img
@include trunk/Identity/Themes/Motifs/Modern/Backgrounds/Img.texi

@node trunk Identity Themes Motifs Modern Backgrounds Tpl
@section trunk/Identity/Themes/Motifs/Modern/Backgrounds/Tpl
@cindex trunk Identity Themes Motifs Modern Backgrounds Tpl
@include trunk/Identity/Themes/Motifs/Modern/Backgrounds/Tpl.texi

@node trunk Identity Themes Motifs Modern Backgrounds Xcf
@section trunk/Identity/Themes/Motifs/Modern/Backgrounds/Xcf
@cindex trunk Identity Themes Motifs Modern Backgrounds Xcf
@include trunk/Identity/Themes/Motifs/Modern/Backgrounds/Xcf.texi

@node trunk Identity Themes Motifs Modern Distro Anaconda Progress
@section trunk/Identity/Themes/Motifs/Modern/Distro/Anaconda/Progress
@cindex trunk Identity Themes Motifs Modern Distro Anaconda Progress
@include trunk/Identity/Themes/Motifs/Modern/Distro/Anaconda/Progress.texi

@node trunk Identity Themes Motifs Modern Palettes
@section trunk/Identity/Themes/Motifs/Modern/Palettes
@cindex trunk Identity Themes Motifs Modern Palettes
@include trunk/Identity/Themes/Motifs/Modern/Palettes.texi

@node trunk Identity Themes Motifs TreeFlower
@section trunk/Identity/Themes/Motifs/TreeFlower
@cindex trunk Identity Themes Motifs TreeFlower
@include trunk/Identity/Themes/Motifs/TreeFlower.texi

@node trunk Identity Themes Motifs TreeFlower Backgrounds
@section trunk/Identity/Themes/Motifs/TreeFlower/Backgrounds
@cindex trunk Identity Themes Motifs TreeFlower Backgrounds
@include trunk/Identity/Themes/Motifs/TreeFlower/Backgrounds.texi

@node trunk Identity Widgets
@section trunk/Identity/Widgets
@cindex trunk Identity Widgets
@include trunk/Identity/Widgets.texi

@node trunk Manuals
@section trunk/Manuals
@cindex trunk Manuals
@include trunk/Manuals.texi

@node trunk Scripts
@section trunk/Scripts
@cindex trunk Scripts
@include trunk/Scripts.texi

@node trunk Scripts Bash
@section trunk/Scripts/Bash
@cindex trunk Scripts Bash
@include trunk/Scripts/Bash.texi

@node trunk Scripts Bash Functions
@section trunk/Scripts/Bash/Functions
@cindex trunk Scripts Bash Functions
@include trunk/Scripts/Bash/Functions.texi

@node trunk Scripts Bash Functions Html
@section trunk/Scripts/Bash/Functions/Html
@cindex trunk Scripts Bash Functions Html
@include trunk/Scripts/Bash/Functions/Html.texi

@node trunk Scripts Bash Functions Locale
@section trunk/Scripts/Bash/Functions/Locale
@cindex trunk Scripts Bash Functions Locale
@include trunk/Scripts/Bash/Functions/Locale.texi

@node trunk Scripts Bash Functions Path
@section trunk/Scripts/Bash/Functions/Path
@cindex trunk Scripts Bash Functions Path
@include trunk/Scripts/Bash/Functions/Path.texi

@node trunk Scripts Bash Functions Render
@section trunk/Scripts/Bash/Functions/Render
@cindex trunk Scripts Bash Functions Render
@include trunk/Scripts/Bash/Functions/Render.texi

@node trunk Scripts Bash Functions Render Config
@section trunk/Scripts/Bash/Functions/Render/Config
@cindex trunk Scripts Bash Functions Render Config
@include trunk/Scripts/Bash/Functions/Render/Config.texi

@node trunk Scripts Bash Functions Shell
@section trunk/Scripts/Bash/Functions/Shell
@cindex trunk Scripts Bash Functions Shell
@include trunk/Scripts/Bash/Functions/Shell.texi

@node trunk Scripts Bash Functions Svg
@section trunk/Scripts/Bash/Functions/Svg
@cindex trunk Scripts Bash Functions Svg
@include trunk/Scripts/Bash/Functions/Svg.texi

@node trunk Scripts Bash Functions Verify
@section trunk/Scripts/Bash/Functions/Verify
@cindex trunk Scripts Bash Functions Verify
@include trunk/Scripts/Bash/Functions/Verify.texi

@node trunk Scripts Bash Locale
@section trunk/Scripts/Bash/Locale
@cindex trunk Scripts Bash Locale
@include trunk/Scripts/Bash/Locale.texi

@node trunk Scripts Perl
@section trunk/Scripts/Perl
@cindex trunk Scripts Perl
@include trunk/Scripts/Perl.texi

@node trunk Scripts Python
@section trunk/Scripts/Python
@cindex trunk Scripts Python
@include trunk/Scripts/Python.texi

@node trunk Translations
@section trunk/Translations
@cindex trunk Translations
@include trunk/Translations.texi

@node trunk Translations Identity
@section trunk/Translations/Identity
@cindex trunk Translations Identity
@include trunk/Translations/Identity.texi

@node trunk Translations Identity Brands
@section trunk/Translations/Identity/Brands
@cindex trunk Translations Identity Brands
@include trunk/Translations/Identity/Brands.texi

@node trunk Translations Identity Brands Tpl
@section trunk/Translations/Identity/Brands/Tpl
@cindex trunk Translations Identity Brands Tpl
@include trunk/Translations/Identity/Brands/Tpl.texi

@node trunk Translations Identity Fonts
@section trunk/Translations/Identity/Fonts
@cindex trunk Translations Identity Fonts
@include trunk/Translations/Identity/Fonts.texi

@node trunk Translations Identity Models
@section trunk/Translations/Identity/Models
@cindex trunk Translations Identity Models
@include trunk/Translations/Identity/Models.texi

@node trunk Translations Identity Release
@section trunk/Translations/Identity/Release
@cindex trunk Translations Identity Release
@include trunk/Translations/Identity/Release.texi

@node trunk Translations Identity Themes
@section trunk/Translations/Identity/Themes
@cindex trunk Translations Identity Themes
@include trunk/Translations/Identity/Themes.texi

@node trunk Translations Identity Themes Backgrounds
@section trunk/Translations/Identity/Themes/Backgrounds
@cindex trunk Translations Identity Themes Backgrounds
@include trunk/Translations/Identity/Themes/Backgrounds.texi

@node trunk Translations Identity Themes Distro Anaconda Progress
@section trunk/Translations/Identity/Themes/Distro/Anaconda/Progress
@cindex trunk Translations Identity Themes Distro Anaconda Progress
@include trunk/Translations/Identity/Themes/Distro/Anaconda/Progress.texi

@node trunk Translations Identity Widgets
@section trunk/Translations/Identity/Widgets
@cindex trunk Translations Identity Widgets
@include trunk/Translations/Identity/Widgets.texi

