Welcome to CentOS 5.8
=====================
The CentOS Project

Abstract
--------

CentOS 5.8 comes with no guarantees or warranties of any sorts, either written
or implied.  The Distribution is released as
file:///usr/share/doc/centos-release-5/GPL[GPL] work.  Individual packages in
the distribution come with their own licences.

What is CentOS?
---------------

http://www.centos.org/[CentOS] is an Enterprise-class Linux Distribution
derived from sources freely provided to the public by a prominent North
American Enterprise Linux vendor.  CentOS conforms fully with the upstream
vendors redistribution policy and aims to be 100% binary compatible.  (CentOS
mainly changes packages to remove upstream vendor branding and artwork.)

CentOS is developed by a small but growing team of core developers. In turn the
core developers are supported by an active user community including system
administrators, network administrators, enterprise users, managers, core Linux
contributors and Linux enthusiasts from around the world.

Advantages
----------

CentOS has numerous advantages including: an active and growing user community,
quickly rebuilt, tested, and QA'ed errata packages, an extensive
http://www.centos.org/modules/tinycontent/index.php?id=15[mirror network],
developers who are contactable and responsive reliable Enterprise Linux class
distribution, multiple free support avenues.

Support
-------
The following free support avenues are available:

- http://www.centos.org/[The CentOS Website]
- http://wiki.centos.org/[The CentOS Wiki] (includes a dynaic http://wiki.centos.org/FAQs[FAQ])
- http://www.centos.org/modules/tinycontent/index.php?id=8[The CentOS IRC Chat]
- http://lists.centos.org/[The CentOS Mailing lists]
- http://forums.centos.org/[The CentOS Forums]
