@node GNU General Public License
@section Licencia P@'ublica General de GNU
@cindex Licencia p@'ublica general GNU
@include trunk/Scripts/Functions/Help/Texinfo/Templates/es_ES/Licenses/GPL.texinfo

@node GNU Free Documentation License
@section Licencia de Documentaci@'on Libre de GNU
@cindex Licencia documentaci@'on libre GNU
@include trunk/Scripts/Functions/Help/Texinfo/Templates/es_ES/Licenses/GFDL.texinfo
