prepare(1)
==========

Name
----
prepare - Standardize configuration tasks.

Synopsis
--------
centos-art.sh prepare [OPTIONS]

Description
-----------
The *prepare* module of *centos-art.sh* script helps you to prepare
the workstation for using the working copy of CentOS artwork
repository. It assumes you've already installed the CentOS
distribution in your workstation and downloaded a working copy of
CentOS artwork repository into it.

Options
-------
The *prepare* module has the following options:

*--help*::
    This option shows the module's documentation (this page).
*--version*::
    This option shows the module's name and version.
*--yes*::
    This option assumes yes to all questions.
*--quiet*::
    This option suppresses all outputs except script's errors.
*--packages*::
    This option verifies whether or not required packages are
    installed in the workstation. When required packages are not
    installed in the workstation, the *prepare* module executes the
    *yum install* command through *sudo* to install the required
    packages.
*--repository*::
    This option calls the *render* module of *centos-art.sh* script
    and produces content for all configuration (+render.conf+) files
    found inside the repository. This option produces images,
    documentation and internal links inside the repository and outside
    it (e.g., to link GIMP's components produced in the repository
    from GIMP's search path).

Reporting Bugs
--------------
Report bugs on the *automation* category of *centos-artwork* project
at the https://centos.org.cu/bugs/[The CentOS Bugs] website.

Author
------
Written by mailto:al@centos.org.cu[Alain Reguera Delgado]

Copyright
---------
Copyright (C) 2013 The CentOS Project

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

// vim: set syntax=asciidoc:
