@node Directorios trunk
@section El directorio @file{trunk}
@cindex Directorios trunk
@include Directorios/trunk.texinfo

@node Directorios trunk Scripts
@section El directorio @file{trunk/Scripts}
@cindex Directorios trunk Scripts
@include Directorios/trunk/Scripts.texinfo

@node Directorios trunk Scripts Functions
@section El directorio @file{trunk/Scripts/Functions}
@cindex Directorios trunk Scripts Functions
@include Directorios/trunk/Scripts/Functions.texinfo

@node Directorios trunk Scripts Functions Help
@section El directorio @file{trunk/Scripts/Functions/Help}
@cindex Directorios trunk Scripts Functions Help
@include Directorios/trunk/Scripts/Functions/Help.texinfo

