[label-install-cd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/label-install.svgz"
locale-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/label-install.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+272.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+737.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+105+417"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+571+417"
media-number    = "6"
media-type      = "CD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[label-install-dvd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/label-install.svgz"
locale-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/label-install.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+272.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+737.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+105+417"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+571+417"
media-number    = "2"
media-type      = "DVD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[label-live-cd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/label-live.svgz"
locale-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/label-live.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+272.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+737.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+105+417"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+571+417"
media-number    = "1"
media-type      = "CD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[label-live-dvd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/label-live.svgz"
locale-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/label-live.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+272.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+737.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+105+417"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+571+417"
media-number    = "1"
media-type      = "DVD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[label-netinstall]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/label-netinstall.svgz"
locale-from     = "${TCAR_BASEDIR}/Artworks/Themes/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/label-netinstall.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+272.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+737.289+255"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+105+417"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/20/centos.png:x20+571+417"
media-number    = "1"
media-type      = "CD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"
