@node Directories
@chapter Los directorios del repositorio
@cindex Directorios

El Repositorio Artístico de CentOS usa directorios para organizar
ficheros y describir ideas relacionadas a la identidad corporativa de
El Proyecto CentOS.  Tales ideas están explicadas en cada una de las
entradas de documentation asociadas a los directorios del repositorio.

En este capítulo usted aprenderá cuáles son los directorios del
repositorio, para qué son y cómo pude utilizarlos. Para comenzar,
seleccione uno de los directorios siguientes para conocer más sobre
él:

@include Directories/chapter-menu.texinfo
@include Directories/chapter-nodes.texinfo
