[sleeve-install-cd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Models/Media/sleeve-install.svgz"
locale-from     = "${TCAR_BASEDIR}/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/sleeve-install.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/24/centos.png:x24+100+568"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+905+204"
media-number    = "6"
media-type      = "CD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[sleeve-install-dvd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Models/Media/sleeve-install.svgz"
locale-from     = "${TCAR_BASEDIR}/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/sleeve-install.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/24/centos.png:x24+100+568"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+905+204"
media-number    = "2"
media-type      = "DVD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[sleeve-live-cd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Models/Media/sleeve-live.svgz"
locale-from     = "${TCAR_BASEDIR}/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/sleeve-live.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/24/centos.png:x24+100+568"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+905+204"
media-number    = "1"
media-type      = "CD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[sleeve-live-dvd]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Models/Media/sleeve-live.svgz"
locale-from     = "${TCAR_BASEDIR}/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/sleeve-live.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/24/centos.png:x24+100+568"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+905+204"
media-number    = "1"
media-type      = "DVD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"

[sleeve-netinstall]
render-type     = "svg"
render-flow     = "media"
render-from     = "${TCAR_BASEDIR}/Models/Media/sleeve-netinstall.svgz"
locale-from     = "${TCAR_BASEDIR}/Models/Media/Locales/${TCAR_SCRIPT_LANG_LC}/sleeve-netinstall.svgz.po"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Types/Default/Final/ffffff/ffffff-0/24/centos.png:x24+100+568"
brand           = "${TCAR_BASEDIR}/Artworks/Brands/Symbols/Default/Final/ffffff/ffffff-0/48/centos.png:x48+905+204"
media-number    = "1"
media-type      = "CD"
media-release   = "5.9 5.10"
media-arch      = "i386 x86_64"
