@node Directories
@chapter The Repository Directories
@cindex Repository directories

The CentOS Artwork Repository uses directories to organize files and
describe idea about The CentOS Project corporate identity. Such ideas
are explained in repository documentation entries which are associated
to each directory inside the repository.

In this chapter you'll learn what each directory inside The CentOS
Artwork Repository is for and how you can make use of them. To start,
take one of the following directories to know more about it:

@include Directories/chapter-menu.texinfo
@include Directories/chapter-nodes.texinfo
