\input texinfo   @c -*-texinfo-*-
@c $Id$
@c -- Header --------------------------------------------------

@setfilename repository.info
@settitle Repositorio Art@'istico de CentOS
@documentlanguage es
@documentencoding ISO-8859-1
@afourpaper
@finalout

@c -- Summary description and copyright -----------------------

@copying
Este manual documenta informaci@'on relevante al desempe@~no, organizaci@'on
y administraci@'on del repositorio art@'istico del proyecto CentOS.

Copyright @copyright{} =COPYRIGHT_YEAR_LIST= =COPYRIGHT_HOLDER=

Se otorga permiso para copiar, distribuir y/o modificar este documento
bajo los t@'erminos de la Licencia de Documentaci@'on Libre de GNU,
Versi@'on 1.1 o cualquier otra versi@'on posterior publicada por la
Free Software Foundation; con las Secciones Invariantes siendo su
LISTE SUS T@'ITULOS, con Textos de Cubierta Delantera siendo LISTA, y
con los Textos de Cubierta Trasera siendo LISTA. Una copia de la
licencia est@'a incluida en la secci@'on titulada ``@ref{GNU Free
Documentation License}''.  
@end copying

@c -- Titlepage, contents, copyright ---------------------------

@titlepage
@title Repositorio Art@'istico de CentOS
@subtitle Manual
@author =COPYRIGHT_HOLDER= 
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@contents

@c -- `Top' node and master menu -------------------------------

@ifnottex
@node Top
@top Repositorio Art@'istico de CentOS
@insertcopying
@end ifnottex

@include repository-menu.texinfo

@c -- The body of the document --------------------------------

@include repository-nodes.texinfo

@c -- The end of the document ---------------------------------

@include repository-index.texinfo

@bye
