\input texinfo   @c -*-texinfo-*-
@c $Id$
@c -- Header --------------------------------------------------

@setfilename repository.info
@settitle Repositorio Artístico de CentOS
@documentlanguage es
@afourpaper
@finalout

@c -- Summary description and copyright -----------------------

@copying
Este manual documenta información relevante al desempeño, organización
y administración del repositorio artístico del proyecto CentOS.

Copyright @copyright{} =COPYRIGHT_YEAR_LIST= =COPYRIGHT_HOLDER=

Se autoriza la copia, distribución y/o modificación de este documento
bajo los términos de la GNU Free Documentation License, Version 1.0 o
cualquier versión publicada posteriormente por la Fundación de
Software Libre; sin secciones invariables, portada, o textos
contraportada. Una copia de la licecia está incluida en la sección
titulada ``GNU Free Documentation License''.
@end copying

@c -- Titlepage, contents, copyright ---------------------------

@titlepage
@title Repositorio Artístico de CentOS
@subtitle Manual
@author =COPYRIGHT_HOLDER= 
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@contents

@c -- `Top' node and master menu -------------------------------

@ifnottex
@node Top
@top Repositorio Artístico de CentOS
@insertcopying
@end ifnottex
@include repository-menu.texinfo

@c -- The body of the document --------------------------------

@include repository-nodes.texinfo

@c -- The end of the document ---------------------------------

@bye
