@node =MANUAL_CHAPTER_NAME=
@chapter Los directorios del repositorio
@cindex =MANUAL_CHAPTER_NAME=
@include =MANUAL_CHAPTER_NAME=/chapter-intro.=FLAG_BACKEND=
@include =MANUAL_CHAPTER_NAME=/chapter-menu.=FLAG_BACKEND=
@include =MANUAL_CHAPTER_NAME=/chapter-nodes.=FLAG_BACKEND=

El repositorio artístico del proyecto CentOS usa directorios para
organizar conceptos sobre su identidad corporativa. Estos conceptos
están explicados an la entrada de documentación relacionada a cada
directorio.

En este capítulo usted aprenderá cuáles son los directorios del
repositorio artístico de CentOS, para qué son y cómo pude hacer uso de
ellos. Para satisfacer tal objetivo, la siguiente lista de directorios
está disponible para que usted pueda explorar:
