@node Directories
@chapter Los directorios del repositorio
@cindex Directorios

El Repositorio Artístico de CentOS usa los directorios para organizar
ficheros y describir ideas conceptuales relacionadas a la identidad
corporativa. Tales ideas conceptuales están explicadas en cada una de
las entradas de documentation asociadas a los directorios del repository.

En este capítulo usted aprenderá cuales son los directorios del
repository, para qué son y cómo pude utilizarlos. De esta forma,
seleccione uno de los directorios siguientes para conocer más sobre
ellos:

@include Directories/chapter-menu.texinfo
@include Directories/chapter-nodes.texinfo
