tcar-prepare(1)
===============

Name
----

tcar-prepare - Prepare the repository workplace.

Synopsis
--------

*centos-art.sh prepare /path/to/your/workplace*

Description
-----------

When you install The CentOS Artwork Repository in your workstation, it
only provides the source files and documentation you need to produce
final content but no way to produce final content inside the location
it was installed. To produce final content using the source files
provided by The CentOS Artwork Repository you need to create a
directory in your workstation where you can store the files you
produce and the configuration files provided by the installed
repository.  This directory is known as the ``repository workplace''
and you should create it using the *prepare* module of *tcar* script.

The *prepare* module creates the workplace in the location you
specified as argument in the command-line. Inside the workplace, there
is one directory for each visual manifestation The CentOS Project is
made of. Each directory inside the workplace might exist to organize
other directories or storing final content. The directories storing
final content hold one configuration file describing how the final
content is produced inside of it. The configuration files inside the
workplace are symbolic links to configuration files inside The CentOS
Artwork Repository installed in your workstation.

The first time you create the workplace using the *prepare* module, it
doesn't include images required to brand other images (e.g., The
CentOS Symbol and The CentOS Type). This is something you need to do
in order for images requiring brand information to be rendered as they
are expected. Rendering images related to brands might consume some
time but it is something that needs to be done just once, unless
variations to brand information be introduced to The CentOS Artwork
Repository, in which case it would be required to render them again to
propagate the changes introduced to brand information the next time
images requiring them be rendered.

[[options]]
Options
-------

The *prepare* module accepts the following options:

*--help*::
    Print module's documentation.

*--version*::
    Print module's version.

Authors
-------

The *prepare* module has received contributions from the following
people:

 * Alain Reguera Delgado <mailto:al@centos.org.cu[al@centos.org.cu]>, 2009-2013

Copyright
---------

Copyright (C) 2009-2013 The CentOS Artwork SIG

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

See Also
--------

tcar(1), tcar-render(1), tcar-locale(1)

// vim: set syntax=asciidoc:
